### ISSUE TITLE
how use it

### ISSUE THREAD

**Issue by Mohamed3bdelwahab** [DuanYuFi/AutoDecoder#1]
how use it bro i try this
python main.py encod.txt
 but it print my code only and stuck on it

**Comment by DuanYuFi** [comment]
> how use it bro i try this python main.py encod.txt but it print my code only and stuck on it

Hi !
Just run the command ``python main.py`` and it will auto decode. However, this is just a studying project, aiming to make a "simplified version" of [cyberchef](https://gchq.github.io/CyberChef/)'s magic module. 
As you mentioned, it outputs nothing and stucked. This is because the decoder didn't get the right answer. I am using BFS to just "search" the correct answer. It's inefficient and not smart. So at most time, encode a message more than three time the code cannot be decoded by using this algorithm. 
Thanks for your issue! If you want to decode something that you don't know the plaintext, try [cyberchef](https://gchq.github.io/CyberChef/)!

**Comment by Mohamed3bdelwahab** [comment]
thank you bro
